### ISSUE TITLE
Lack of description for empty result set causes SQLAlchemy exception

### ISSUE THREAD

**Issue by john-bodley** [druid-io/pydruid#151]
SQLAlchemy throws an `AttributeError` when fetching from a [ResultProxy](https://docs.sqlalchemy.org/en/latest/core/connections.html#sqlalchemy.engine.ResultProxy) when the underlying Druid query results in an empty result set, e.g. no rows, as the proxy is prematurely closed, i.e., 
```
>>> from sqlalchemy.engine import create_engine

>>> engine = create_engine('druid://localhost:8082/druid/v2/sql')
>>> result = engine.execute("SELECT SUM(x) FROM foo WHERE bar IS NULL")
>>> result.fetchall()
...
AttributeError: 'NoneType' object has no attribute 'fetchall'
```
The reason the ResultProxy is closed is because `cursor.description` is [`None`](https://github.com/sqlalchemy/sqlalchemy/blob/66e88d30a86fc37e2eaf7367e988ced3834e3250/lib/sqlalchemy/engine/result.py#L879). This results in `result.cursor` being `None` which is why the exception is thrown. 

It seems that other dialects have a description irrespective of whether there are rows and hence don't suffer from the same issue. Note I'm uncertain whether there's even a viable solution as the Druid SQL REST API doesn't provide this information for an empty result set, 
```
> cat query.json
{"query": "SELECT SUM(x) FROM foo WHERE bar IS NULL"}

> curl -XPOST -H 'Content-Type: application/json' http://localhost:8082/druid/v2/sql/ -d @query.json
[]
```

Note I no one can circumvent this issue by using a raw connection, however this example illustrates the behavior that Pandas uses for reading SQL.

to: @betodealmeida @mistercrunch

**Comment by betodealmeida** [comment]
@john-bodley note that `cursor.description` should be `None` in this case:

> This attribute will be None for operations that do not return rows or if the cursor has not had an operation invoked via the .execute*() method yet. (https://www.python.org/dev/peps/pep-0249/#description)

**Comment by betodealmeida** [comment]
Maybe we're missing something in the SQLAlchemy dialect?

**Comment by betodealmeida** [comment]
@john-bodley note too that `.fetchall()` **should** return an exception when no rows are returned:

> An Error (or subclass) exception is raised if the previous call to .execute*() did not produce any result set or no call was issued yet. (https://www.python.org/dev/peps/pep-0249/#fetchall)

So I think this is behaving as expected.

**Comment by john-bodley** [comment]
@betodealmeida the `fetchall` isn’t throwing the exception, but instead the underlying cursor is `None` because it’s prematurely closed.

**Comment by betodealmeida** [comment]
@john-bodley but my point is, you should always wrap your `.fetchall()` in a `try/except` block, in case zero rows were returned.

**Comment by john-bodley** [comment]
@betodealmeida note's it's the ResultProxy [`fetchall`](https://github.com/sqlalchemy/sqlalchemy/blob/66e88d30a86fc37e2eaf7367e988ced3834e3250/lib/sqlalchemy/engine/result.py#L1195) method that I'm calling which wraps the underlying DBAPI and has slightly different behavior (per the [documentation](https://docs.sqlalchemy.org/en/latest/core/connections.html#sqlalchemy.engine.ResultProxy.fetchall)). 

> Fetch all rows, just like DB-API cursor.fetchall().
>
> After all rows have been exhausted, the underlying DBAPI cursor resource is released, and the object may be safely discarded.
> 
> Subsequent calls to ResultProxy.fetchall() will return an empty list. After the ResultProxy.close() method is called, the method will raise ResourceClosedError.

I plan to do some more digging to see why this is happening. Note both SQLite and Presto behave differently, i.e., an exception isn't thrown when the result set is empty.

**Comment by john-bodley** [comment]
@betodealmeida I created https://github.com/sqlalchemy/sqlalchemy/issues/4523 to discuss how one should handle an empty result set associated with a SELECT statement when no description is available.

**Comment by john-bodley** [comment]
@betodealmeida it seems that https://github.com/apache/incubator-druid/pull/6191 will help remedy the solution as the SQL interface provides a mechanism for returning the column names via the `X-Druid-Column-Names` header.

**Comment by Makesh-Gmak** [comment]
@john-bodley : I am also impacted by this issue. I am currently using Druid 0.13.0. But still I am not receiving `X-Druid-Column-Names` header  in my response. Any druid config file need to be updated for this ?

**Comment by Makesh-Gmak** [comment]
As a part of this bug (https://github.com/apache/incubator-druid/issues/6409,) , it looks like they  moved the column info to response body  which can be seen by setting `"header" : true` in the request, which will never return empty response.

The below query will return 1 row with all columns
**Query**
```
{
  "query":"SELECT delta, page, added, deleted FROM wikipedia   WHERE 1=0  ",
  "resultFormat" : "object",
  "header" : true
}
```
**Result**
```
[
    {
        "delta": null,
        "page": null,
        "added": null,
        "deleted": null
    }
]
```

**Comment by john-bodley** [comment]
@Makesh-Gmak we're currently not using Druid 0.13.0 though I'm trying to push for an upgrade. When this happens I was planning on making a change to `pydruid` to support using the header. 

It seems including the `header` in the request for older versions doesn't break things and thus the change should be fairly simple, i.e., if a header is present use it to define the description, otherwise revert to using the current logic.

**Comment by Makesh-Gmak** [comment]
Thanks for the resolution. When will be the next release ?
