### ISSUE TITLE
Missing params Key in SCAN Query

### ISSUE THREAD

**Issue by JustFeng** [druid-io/pydruid#205]
druid/processing/src/main/java/org/apache/druid/query/scan/ScanQuery.java 
scan query has a param named 'order' is invalid in pydruid scan()method
Druid is support this query param in non-legacy scan query mode 

please add 'order' in  pydruid query Query scan valid_parts

**Comment by MSadeghzadehG** [comment]
I'm working on it...

**Comment by MSadeghzadehG** [comment]
I think #207 will fix it.

**Comment by MSadeghzadehG** [comment]
#183 merged. you can close the issue.
