### ISSUE TITLE
module 'pydruid.client' has no attribute 'time_boundary' and 'segment_metadata'

### ISSUE THREAD

**Issue by Keyrainn** [druid-io/pydruid#223]
pydruid vesion : 0.6.0
I'm following the example from [pydruid documentation](https://pythonhosted.org/pydruid/#module-pydruid.client) example. Seems like the `segment_metadata` and `time_boundary` module returns `AttributeError: module 'pydruid.client' has no attribute` error.

FYI these are the imports that i use :

`from pydruid.utils.postaggregator import *
from pydruid.utils.aggregators import *
from pydruid.query import QueryBuilder
from pydruid.utils.filters import *
from pydruid.client import *
from pylab import plt
from pydruid import *`

**Comment by mistercrunch** [comment]
ok `0.6.1` is out and should address this
