### ISSUE TITLE
Is it possible to support merge property in segment metadata query?

### ISSUE THREAD

**Issue by noppanit** [druid-io/pydruid#64]
Is it possible to support `merge` in `segment_metadata? 

https://github.com/druid-io/pydruid/blob/f9645c9eaa7848410c08a13079b67f4450d2b642/pydruid/query.py#L336

If yes, I can make a PR.

**Comment by noppanit** [comment]
@RichRadics Thanks! When will this be merged?

**Comment by nishantmonu51** [comment]
closed by - https://github.com/druid-io/pydruid/pull/67
