### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by se7entyse7en** [druid-io/pydruid#65]
Is it possibile to bump a new version (maybe `0.3.1`) including the in filter support?

**Comment by fjy** [comment]
@se7entyse7en can you submit a PR?

**Comment by dakra** [comment]
I assume he just means to increase the version number in setup.py https://github.com/druid-io/pydruid/blob/master/setup.py#L39 and make a release.

Don't think a pull request is necessary for that, especially since someone from the pydruid team has to upload the new version to pypi anyway.

**Comment by se7entyse7en** [comment]
@dakra exactly

**Comment by mistercrunch** [comment]
+1 https://github.com/airbnb/superset maintainer here. I'm very familiar with the Pypi deploy process if you guys want to give me rights on the package and the repo I could take this on when needed.

**Comment by gianm** [comment]
Right now only a couple people have rights to the package, I'll see if I can get a hold of one of them.

**Comment by dkhwangbo** [comment]
+1 !

**Comment by gianm** [comment]
0.3.1 is now up on pypi.
