### ISSUE TITLE
Custom duration granularities?

### ISSUE THREAD

**Issue by azymnis** [druid-io/pydruid#83]
Based on what I read in the [docs](http://druid.io/docs/latest/querying/granularities.html), Druid supports custom granularities like this:

```
{"type": "duration", "duration": 7200000}
```

Is there support for that in PyDruid?

**Comment by dakra** [comment]
Sure, pydruid just passes whatever you put to `granularity` to druid. So, for example, you can just do `druid.groupby(...., granularity={"type": "duration", "duration": 7200000}, ....)`

**Comment by azymnis** [comment]
Oh you just json serialize all fields of the query... Ok that makes sense, thanks. Might be good to document that somewhere
