### ISSUE TITLE
Support for 'interval' filter.

### ISSUE THREAD

**Issue by var23rav** [druid-io/pydruid#85]
**Is there any 'Interval Filter' available ?**

I couldn't find it in **"type" : "interval"** in [filter](https://github.com/druid-io/pydruid/blob/master/pydruid/utils/filters.py) code.

Filtering on a set of ISO 8601 intervals:

```
{
    "type" : "interval",
    "dimension" : "__time",
    "intervals" : [
      "2014-10-01T00:00:00.000Z/2014-10-07T00:00:00.000Z",
      "2014-11-15T00:00:00.000Z/2014-11-16T00:00:00.000Z"
    ]
}
```

**Comment by gianm** [comment]
@var23rav, it's probably missing. A PR would be welcome!

**Comment by var23rav** [comment]
Initiated a PR [#87](https://github.com/druid-io/pydruid/pull/87)

**Comment by var23rav** [comment]
Closing since feature is available with  [PR 87 code merged](https://github.com/druid-io/pydruid/commit/2420109553812470ed4d91cd0f8d5e70bbf2cfd3).
