### ISSUE TITLE
PyDruid 0.3.2?

### ISSUE THREAD

**Issue by joshwalters** [druid-io/pydruid#89]
With the merge of https://github.com/druid-io/pydruid/pull/72 we now have the ability to perform theta sketch operations. This functionality is needed in [Superset](https://github.com/airbnb/superset), but we need a new PyDruid pip package to be pushed so that we can use this new feature.

Is there a release process / timeline to get a new package pushed? Is there anything I can do to help? My understand is that the `setup.py` script needs to be modified to list `0.3.2` and a git tag is added for that version.

**Comment by gianm** [comment]
pydruid doesn't really have much of a process. All it takes is a vote on the druid-development group and someone to volunteer to do the release. I'll start the vote -- look for it there. You can help by voting and by testing the build and reporting whether or not it works for you.

**Comment by gianm** [comment]
Vote thread: https://groups.google.com/forum/#!forum/druid-development

**Comment by joshwalters** [comment]
Thanks for the help @gianm! I will chime in on the vote thread.
